### ISSUE TITLE
Issue: Can't resolve 'd3' when execute ng serve

### ISSUE THREAD

**Issue by RyanZhou713** [adedayo/ngx-liquid-gauge#1]
Hi @adedayo

Thanks for your time to write this amazing gauge!

But after install ngx-liquid-gauge with angular-cli,  angular app compile failure, log printed as below,

**ERROR in ./node_modules/ngx-liquid-gauge/fesm5/ngx-liquid-gauge.js
Module not found: Error: Can't resolve 'd3' in 'D:\3 NodeJs_project\\node_modules\ngx-liquid-gauge\fesm5'
i ｢wdm｣: Failed to compile.**

we can install d3 with npm first to solve this problem, but I cannot find the description in your readme file.
I advise you can add ' npm install d3 --save ' dependence in your readme for help others.

Thanks!

**Comment by adedayo** [comment]
Thank you @RyanZhou713 

The README dependencies section (at the bottom) already mentioned that Angular and D3 as dependencies for the component. However, I have now also emphasised that it needs to be installed with the npm instruction as you suggested :-) 

Many thanks.

Kind regards,
Dayo
