### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by lucbonnin** [adedayo/ngx-liquid-gauge#2]
I'm trying to use ngx-liquid-gauge with a ionic3 app.
i've installed d3 and ngx-liquid-gauge and added ngx-liquid-gauge in my app.module.ts.
(+added it in my page.ts)
Then i've tried to simply add a simple html element 
 <lib-ngx-liquid-gauge
            [value]="77">
 </lib-ngx-liquid-gauge>

When i've simply run "ionic serve" (to run the app), at the starting (i suppose when loading your lib), i've a blocking issue

"Object(...) is not a function"

```
Uncaught TypeError: Object(...) is not a function
    at ngx-liquid-gauge.js:18
    at Object.<anonymous> (ngx-liquid-gauge.js:20)
    at __webpack_require__ (bootstrap 7b4d8e9c9037c30cdbdc:54)
    at Object.570 (main.ts:5)
    at __webpack_require__ (bootstrap 7b4d8e9c9037c30cdbdc:54)
    at Object.565 (main.ts:1)
    at __webpack_require__ (bootstrap 7b4d8e9c9037c30cdbdc:54)
    at webpackJsonpCallback (bootstrap 7b4d8e9c9037c30cdbdc:25)
    at main.js:1
```

ngx-liquid-gauge.js line 18.

What can i do ?

**Comment by adedayo** [comment]
Hello can you share your html please?

Please note:

> <lib-ngx-liquid-gauge [value]="77"> 

is not a complete html element. I am presuming you "closed" the element.

Also, please note that the component has a dependency of Angular 6 and above.

Kind regards

**Comment by lucbonnin** [comment]
@adedayo  Yes i've closed the <lib-ngx-liquid-gauge> element.
Ionic3 is based on angular 3 o 4, not 6. So i think i'm not compliant for this reason :(
I will be forced to use another plugin such as https://github.com/ashish-chopra/ngx-gauge
that's seems to be ok (but not liquidifying the gauge :(   )

**Comment by adedayo** [comment]
Really sorry about this. I could look at seeing if I could support older Angular versions, could you upgrade your Ionic too to a newer Angular release?

**Comment by lucbonnin** [comment]
Unfortunately not. As ionic is based on angular and also a bunch of cordova plugins that are not all up to date and angular>4 ready.

**Comment by adedayo** [comment]
Ah, I see :-(

I've released version 2.0.3 with a preemptive support for lower angular versions: 4 and 5. Not sure it will work, but please give it a spin.

**Comment by adedayo** [comment]
I will close in the meantime ...

**Comment by adedayo** [comment]
By the way @lucbonnin , this project uses the older revision of the component successfully in ionic 3: https://github.com/kemokemo/d3LiquidGaugeApp. 

You might be able to get some ideas from them
