### ISSUE TITLE
the attributes can not work in the lib-ngx-liquid-gauge 

### ISSUE THREAD

**Issue by ChunHsiungHsu** [adedayo/ngx-liquid-gauge#29]
Hi 
Using lib-ngx-liquid-gauge in my component, got this errors with underline RED color in the editors.

The message is =>
Property 'minValue' is private and only accessible within class 'NgxLiquidGaugeComponent'

Checking /nodes/ngx-liquid-auage, the attribute scope is private.

Enviorments:
Angular 12.x

can you help me to solve it?

**Comment by adedayo** [comment]
Hello @ChunHsiungHsu ,

 Thanks for your comments. The attribute is private and if you want to set the value, that should be done via the input properties of the angular component. Please see the demo examples to see how to set these.
 
 Kind regards,
 Dayo
