### ISSUE TITLE
Input properties are private

### ISSUE THREAD

**Issue by alejandroaap** [adedayo/ngx-liquid-gauge#30]
Why are (Input) properties private? Shouldn't they be public?

I have run your test example and am getting the following error

![image](https://user-images.githubusercontent.com/19358188/137714974-6d1c172f-3b4f-4c44-9c59-375919e52550.png)

Thanks

**Comment by adedayo** [comment]
Can you share your code please? Especially, the package.json.

Which version are you using?

Kind regards

**Comment by adedayo** [comment]
Closing ..., please re-open if issue persists.

Kind regards
