### ISSUE TITLE
Cannot change chart shape

### ISSUE THREAD

**Issue by HenriqueMessias** [adedayo/ngx-liquid-gauge#31]
Hello, I would like to know how to change the shape of the gauge. I would like a rect instead of a circle

**Comment by adedayo** [comment]
Hello,

 The component does not support different shapes, but it is doable if you really wanted to implement a different shape. This is where you need to look at: https://github.com/adedayo/ngx-liquid-gauge/blob/08452e873b58ef719e54e0d611c76e952761d1c1/projects/ngx-liquid-gauge/src/lib/liquidFillGauge.ts#L108
 
 Kind regards,
 Dayo
