### ISSUE TITLE
Is there any option to hide outer circle of chart

### ISSUE THREAD

**Issue by logamuhilanMobitech** [adedayo/ngx-liquid-gauge#32]
Hi, I just using this package in my angular project, which was awesome. But I have an issues with it.

1. Chart  is always aligned to the right end, how to customize the alignment.
2. I have no choice why the outer circle of the chart is there, is there any way to remove/Hide the outer circle. *refer Screenshot

kindly help me with this...

![image](https://user-images.githubusercontent.com/116332467/197115959-ef6ac073-c54b-4ad4-a4a4-484c32442c6a.png)

**Comment by logamuhilanMobitech** [comment]
I have fixed this issue by myself. What happened was Angular setting a Div element with a class='center' . That's the problem.

**Comment by adedayo** [comment]
Thank you @logamuhilanMobitech for the feedback
