### ISSUE TITLE
Gauge size or responsive

### ISSUE THREAD

**Issue by evallgar** [adedayo/ngx-liquid-gauge#4]
Please excuse me If my question is senseless.

I'm both new to this gauge and never used D3 before. So i'm a bit lost here.

How can I set the gauge size to either an specified width and height or/ responsive.

Thanks.

**Comment by adedayo** [comment]
Hello @evallgar ,

You could use standard css style to scale the component. Here is an example:

Here I assign a class named **sample**
```html
<lib-ngx-liquid-gauge class="sample" [value]="'30'"></lib-ngx-liquid-gauge>
```
Then you could apply a scaling transform to that class in your .css  as follows
```css
:host ::ng-deep  .sample > div > svg {
transform: scale(1.2);
}
```

I hope that is helpful.

Kind regards!

**Comment by adedayo** [comment]
However, that was something I did not consider: adjusting the size of the gauge. If you'd like to contribute, I will gratefully accept. 

Or if I get some time I could add a "scale" attribute to the component to adjust the size.

Kind regards
