### ISSUE TITLE
Not working properly in safari browser and ios devices

### ISSUE THREAD

**Issue by srinivaskona** [adedayo/ngx-liquid-gauge#5]
while comparing chrome and safari browsers, working fine in chrome. but safari always showing as filled.

![image](https://user-images.githubusercontent.com/16757336/70878552-f534b500-1fe7-11ea-8ff3-5ed9f2120f2c.png)

**Comment by adedayo** [comment]
Hello @srinivaskona ,

 Can you kindly provide more information about your angular versions, d3 version perhaps provide code snippets, if appropriate?

Many thanks.

**Comment by adedayo** [comment]
Kindly reopen as may be necessary.
